In [1]:
import pandas as pd

In [9]:
df = pd.read_excel(r"C:\Users\US3R\OneDrive\Dokumen\data-science\Project\sumateranomics\nlp\nlp_pipeline_v2\data\validation\sample_200_for_annotation.xlsx")

In [10]:
df

,article_id,published_date,source,title,full_text,gpt_label,gpt_sentiment_score,human_label,human_sentiment_score,human_notes
0,977ffc9dc5e9722a,2023-11-14,detik.com,NaN,Harga cabai rawit di Sumut masih terpantau mah...,PRICEREPORT,0.7,NaN,NaN,NaN
1,29dad7e7b815cfe3,2025-11-13,detik.com,NaN,Nasi goreng adalah masakan yang telah dikenal ...,IRRELEVANT,0.0,NaN,NaN,NaN
2,147f6c3197c1f98b,2023-10-15,detik.com,NaN,Suku Karo dikenal memiliki banyak makanan unik...,IRRELEVANT,0.0,NaN,NaN,NaN
3,d17cfbdef09a2329,2022-04-01,antaranews.com,NaN,Jakarta (ANTARA) - Pemerintah akan menyalurkan...,SUPPLYSHOCK,0.8,NaN,NaN,NaN
4,09afc5ea94089b97,2025-10-13,antaranews.com,NaN,Jakarta (ANTARA) - Beras Bulog adalah beras ya...,SUPPLYSHOCK,-0.4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
195,f9db567f2bcecb59,2023-12-21,antaranews.com,NaN,Jakarta (ANTARA) - Pabrik penggilingan gandum ...,IRRELEVANT,0.0,NaN,NaN,NaN
196,6e3e1ab47976b10d,2023-05-02,antaranews.com,NaN,Besaran NTP pada April ini ditopang dari NTP s...,PRICEREPORT,-0.2,NaN,NaN,NaN
197,6f39596b0bac5f15,2021-11-25,food.detik.com,NaN,Mau makan siang spesial? Semangkuk soto medan ...,IRRELEVANT,0.0,NaN,NaN,NaN
198,273a0da06dab72c0,2024-05-20,dailyklik.id,Harga Bawang Putih di Medan Lebih Mahal hingga...,Harga Bawang Putih di Medan Lebih Mahal hingga...,PRICEREPORT,0.7,NaN,NaN,NaN
199,c1f29b4ee2e4b6f0,2023-11-10,antaranews.com,NaN,Medan (ANTARA) - Perum Bulog Kanwil Sumatera U...,SUPPLYSHOCK,0.2,NaN,NaN,NaN

In [4]:
df2 = pd.read_parquet(r"data\processed\extractions_clean.parquet")
df2

,article_id,url,source,title,published_date,full_text,char_length,keyword_matched,label,sentiment_score,confidence,commodities,supply_location,is_forward_looking,rationale,model,tokens_prompt,tokens_completion,extraction_status
0,7a09e533e5974c64,https://www.antaranews.com/berita/5442698/mend...,antaranews.com,,2026-02-27,Medan (ANTARA) - Menteri Perdagangan (Mendag) ...,2788,[harga ayam],PRICEREPORT,-0.2,0.90,"[sayur-mayur, cabai merah, bawang merah, bawan...","Tebing Tinggi, Sumatera Utara",False,Artikel melaporkan kunjungan Mendag ke Tebing ...,gpt-5-mini-2025-08-07,2760,1359,success
1,3e3f6d4c1f450c50,https://www.antaranews.com/berita/5439926/satg...,antaranews.com,,2026-02-26,Jakarta (ANTARA) - Satgas Sapu Bersih (Saber) ...,3654,[],IRRELEVANT,0.0,0.82,"[daging sapi, daging ayam, beras]",Kepulauan Riau (Kepri); Nusa Tenggara Barat (N...,False,Artikel adalah laporan penegakan dan temuan pe...,gpt-5-mini-2025-08-07,2999,1635,success
2,c91352b9209eb9ba,https://www.antaranews.com/berita/5432946/mend...,antaranews.com,,2026-02-23,Jakarta (ANTARA) - Menteri Perdagangan (Mendag...,2488,[],PRICEREPORT,0.2,0.85,"[beras, daging ayam, telur ayam, bawang merah,...","Medan, Sumatera Utara",False,Artikel merupakan laporan harga dan kondisi pa...,gpt-5-mini-2025-08-07,2721,1682,success
3,82aead26d248fef8,https://www.antaranews.com/berita/5429422/bulo...,antaranews.com,,2026-02-21,Realisasi penyerapan jagung pipil mulai mening...,2320,[],SUPPLYSHOCK,-0.1,0.75,"[jagung pipil, gabah, beras, telur ayam]","Sumatera Utara (Deli Serdang, Padang Lawas, Ba...",True,Laporan menyorot intervensi Bulog dan stok jag...,gpt-5-mini-2025-08-07,2657,1940,success
4,3248d6de609c93ce,https://www.antaranews.com/berita/5425062/khof...,antaranews.com,,2026-02-19,Kami melihat beberapa item yang membutuhkan pe...,3332,"[harga cabai, harga telur, harga ayam]",IRRELEVANT,0.0,0.90,"[telur ayam, daging ayam, beras, minyak goreng...","Pasar Larangan, Sidoarjo, Jawa Timur",False,Meskipun artikel membahas harga dan pasokan be...,gpt-5-mini-2025-08-07,2944,1325,success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,cccdfb259a317175,https://food.detik.com/info-kuliner/d-7282755/...,food.detik.com,,2024-04-07,"Kalau bosan dengan menu opor ayam, hidangan Ka...",4310,[],IRRELEVANT,0.0,0.88,"[daging ayam, bawang merah, bawang putih, miny...",None,False,Artikel adalah resep Kari Ayam Bakar (kuliner)...,gpt-5-mini-2025-08-07,3145,1585,success
2157,46744f799eb4ca78,https://www.detik.com/sumut/berita/d-7215176/4...,detik.com,,2024-02-28,Warung kopi (Warkop) di Medan akhir-akhir ini ...,3794,[],IRRELEVANT,0.0,0.90,"[daging ayam, beras, telur ayam]",None,False,Artikel adalah fitur kuliner tentang warkop di...,gpt-5-mini-2025-08-07,3093,1962,success
2158,e295c734878c951c,https://okemedan.com/2021/04/05/tpid-tinjau-pu...,okemedan.com,TPID Tinjau Pusat Pasar Inpres Lhokseumawe - O...,2021-04-05,LHOKSEUMAWE I okemedan. Menjelang bulan suci r...,1818,[],PRICEREPORT,0.2,0.72,"[beras, cabai merah, bawang merah]",Sumatera Utara,False,Artikel terutama melaporkan perubahan harga ak...,gpt-5-mini-2025-08-07,2557,1975,success
2159,326470fcb1020765,https://food.detik.com/info-kuliner/d-7050558/...,food.detik.com,,2023-11-22,"Rindu masakan nusantara, pria Indonesia yang b...",3535,[],IRRELEVANT,0.0,0.92,"[daging sapi, daging ayam, beras, cabai]",None,False,Artikel adalah fitur kuliner tentang restoran ...,gpt-5-mini-2025-08-07,2958,1842,success
2160,d74d20a9a9376965,https://food.detik.com/rumah-makan/d-5689356/n...,food.detik.com,,2021-08-20,Nasi galung mungkin tidak sepopuler nasi Padan...,6724,[],IRRELEVANT,0.0,0.88,"[beras, cabai rawit, telur ayam, daging ayam, ...",None,False,Artikel adalah liputan kuliner tentang Nasi Ga...,gpt-5-mini-2025-08-07,3812,2595,success

In [11]:
df2 = df2.sort_values(by='published_date', ascending=True)

In [24]:
df2['full_text'].iloc[1471]

'Di kawasan Jakarta Barat ada bakery legendaris yang menawarkan roti klasik empuk dan lembut. Sudah buka sejak tahun 1970-an, masih eksis sampai sekarang.\nDi tengah kemunculan banyak bakery kekinian, sejumlah bakery atau toko roti legendaris juga masih ada yang eksis sampai saat ini. Salah satunya bakery-bakery legendaris di kawasan Jakarta Barat.\nBuka sejak tahun 1970-1980 an, bakery ini terkenal menawarkan roti dengan adonan empuk dan lembut. Banyak varian rasa dihadirkan dengan beberapa masih dibuat menggunakan metode tradisional, tetapi ada juga yang sudah berinovasi menjadi lebih modern.\nBerikut 5 bakery legendaris di Jakarta Barat yang masih eksis karena kelezatan menunya!\n1. Suisse Bakery\nSuisse Bakery merupakan salah satu toko roti tertua di kawasan Jakarta Barat. Sudah beroperasi sejak tahun 1978.\nDari dulu sampai sekarang toko roti ini masih populer di kalangan banyak pelanggan.\nSemua rotinya dibuat fresh, dan tersusun rapi di etalase. Pelanggan bisa pilih dan ambil sendiri roti yang diinginkan.\nPilihannya beragam, mulai dari yang manis sampai gurih. Ada Long John yang paling favorit. Untuk pilihan gurih, bisa coba variasi abon sapi atau baso sapi.\nSelain roti, mereka juga punya pilihan jajanan zaman dulu yang tidak kalah enak, seperti risoles, kroket ayam, bika ambon, dan lain sebagainya.\nHarga aneka roti dibanderol mulai dari Rp 11.000. Lokasinya di Jl. Hayam Wuruk No.10 5-6, RT.10/RW.9, Maphar, Kec. Taman Sari, Kota Jakarta Barat. Buka setiap hari pukul 07.00-22.00 WIB.\n2. Delicious Bakery\nSejak 1986, Delicious Bakery menawarkan roti lembut dan berkualitas. Memang sempat tutup, tetapi mereka kembali buka menyajikan roti favorit banyak orang.\nKetika mencicipi roti di bakery legendaris ini, banyak pelanggan yang langsung bernostalgia. Rasanya mengingatkan mereka kepada roti-roti yang biasa dimakan saat kecil.\nBakerynya juga punya nuansa ala tahun 80-an. Pelanggan bisa memilih sendiri roti yang diinginkan.\nRotinya juga dipanggang berkala sehingga tersaji segar. Pilihannya beragam, mulai dari roti Long John dengan berbagai varian, chiffon cake mocca, roti abon, roti bakso ayam spesial dan masih banyak lagi.\nMereka juga menyajikan pilihan cake bergaya jadul, dengan variasi mocha hingga black forest.\nHarga rotinya dibanderol mulai dari Rp 9.000 saja. Delicious Bakery beralamat di Jl. Hayam Wuruk No.64-65 9, RT.9/RW.4, Maphar, Kec. Taman Sari, Kota Jakarta Barat. Buka setiap hari mulai pukul 06.30 - 21.00 WIB.\nBakery legendaris di Jakarta Barat lainnya bisa dilihat pada halaman selanjutnya!\n3. Elisa Bakery\nToko roti ini memang lokasinya agak nyempil, tetapi terkenal dengan kelezatannya. Memang berawal dari usaha roti kecil-kecilan, tetapi sedikit demi sedikit berkembang.\nTerlebih ketika banyak food vlogger mampir, toko roti legendaris ini akhirnya mendapat perhatian lebih dari banyak orang. Sampai sempat viral di media sosial.\nBuka sejak 1978, Elisa Bakery menawarkan roti jadul lembut dengan 36 varian rasa. Mulai dari cokelat, keju, pisang cokelat, bakso ayam telur asin, dan masih banyak lagi.\nSemua rotinya juga disajikan hangat \'fresh from the oven.\' Harganya dibanderol mulai dari Rp 8.000- Rp 17.000.\nLokasinya di Jl. Pejagalan III No.5, RT.2/RW.4, Pekojan, Kec. Tambora, Kota Jakarta Barat. Buka Senin-Sabtu pukul 06.00 - 13.00 WIB.\n4. Capital Bakery\nCapital Bakery juga merupakan salah satu bakery legendaris yang bisa ditemui di Jakarta Barat. Awalnya buka di Medan tahun 1980-an, lalu pindah ke Jakarta tahun 1989.\nBakery ini menawarkan berbagai macam roti dan kue yang cocok untuk segala acara.\nRoti klasiknya bisa dicoba, seperti roti nanas, selai kacang, donat sate, pisang cokelat keju, daging sapi, dan masih banyak lagi. Seiring berjalannya waktu, Capital Bakery menciptakan inovasi rasa lebih beragam. Kini ada variasi chocolate pistachio kunafa hingga Korean red bean.\nHarga rotinya dibanderol mulai dari harga Rp 11.000. Jika tertarik bisa menyambangi salah satu cabangnya di Jl. Pesanggrahan No.26 1, RT.2/RW.7, Kembangan Sel., Kec. Kembangan, Kota Jakarta Barat.\n5. Kantin Mira\nKantin Mira juga termasuk salah satu yang legendaris di Jakarta Barat. Sudah beroperasi sejak tahun 1987.\nKantin Mira menawarkan berbagai variasi roti yang empuk, dengan serat lembut. Pilihan rotinya mulai dari roti keju, cokelat, cokelat keju, goreng ayam, abon, kacang ijo, kacang merah, dan lain sebagainya.\nSelain roti, mereka juga punya kue lain, seperti muffin, soes, hingga donat. Harganya juga masih ramah dikantong, dibanderol mulai dari Rp 7 ribuan saja.\nToko roti ini bisa ditemui di Jl. Mandala Raya No.20D 13, RT.13/RW.5, Tomang, Kec. Grogol petamburan, Kota Jakarta Barat. Buka setiap hari pukul 07.00-17.00 WIB.\nSimak Video "Antre Panjang Demi Mencicipi Cold Milk Bun yang Viral"\n[Gambas:Video 20detik]\n(aqr/adr)'

72701

In [16]:
df2[df2['published_date']=='2026-02-03']

,article_id,url,source,title,published_date,full_text,char_length,keyword_matched,label,sentiment_score,confidence,commodities,supply_location,is_forward_looking,rationale,model,tokens_prompt,tokens_completion,extraction_status
554,e9420c3fa45346c2,https://www.detik.com/sumut/berita/d-8339307/h...,detik.com,,2026-02-03,Harga cabai merah terus merangkak naik pada pe...,1560,[harga cabai],PRICEREPORT,0.7,0.90,"[cabai merah, cabai rawit]","Sumatera Utara (termasuk Tapanuli Selatan, Nia...",False,Artikel hanya melaporkan harga cabai merah yan...,gpt-5-mini-2025-08-07,2498,1205,success
1471,65d7537b96e627ac,https://rri.co.id/medan/keuangan/2156038/sumut...,rri.co.id,"Sumut Deflasi Januari, Waspada Inflasi Februar...",2026-02-03,"Sumut Deflasi Januari, Waspada Inflasi Februar...",2108,[harga cabai],SUPPLYSHOCK,0.5,0.95,"[cabai merah, cabai hijau, minyak goreng curah...",Sumatera Utara,True,Artikel memprediksi potensi inflasi pangan di ...,gemini-3.1-flash-lite-preview,2625,386,success
1440,b942a77e70b2ac3a,https://mediaindonesia.com/nusantara/856600/kr...,mediaindonesia.com,Krisis dan Harga Cabai Merah Sumbang Inflasi d...,2026-02-03,Headline\nSERANGAN brutal dan mematikan dari I...,4095,"[harga cabai, inflasi Sumut]",SUPPLYSHOCK,0.6,0.90,"[cabai merah, cabai hijau, cabai rawit, minyak...",Sumatera Utara (produksi lokal cabai menurun);...,True,Artikel mengindikasikan penurunan produksi cab...,gpt-5-mini-2025-08-07,3124,1538,success